### ISSUE TITLE
Document the difference between standalone and embeddable output (header_footer documentation)

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor.org#171]
See the security section for the commented text

**Comment by jaredmorgs** [comment]
@mojavelinux please assign this issue to me.

**Comment by mojavelinux** [comment]
I don't think the topic of this issue is clear, so I will attempt to give it some direction.

We need to document the different between standalone output and embeddable output. This is controlled using the `header_footer` option (which can only be set from the CLI or API). When the `header_footer` is enabled, the converter generates a standalone document. When the `header_footer` is disabled, the converter generates an embeddable document.

Here's how I describe the difference between the two.

The standalone output provides the framing around the content, which includes styling and all the library integrations that the content needs to properly render (e.g., MathJax, the default stylesheet, etc). When you produce an embeddable document, you only get the body content. It's up to you to provide the framing, including the styling and library integrations.

**Comment by mojavelinux** [comment]
It's also important to note that the default for the `header_footer` option is circumstance dependent.

* asciidoctor CLI - enabled by default
* asciidoctor API
  * enabled by default if writing to a file (to_file)
  * disabled by default otherwise
* disabled on GitHub and anywhere else the content is being embedded
