### ISSUE TITLE
asciidoctor -h should list backends

### ISSUE THREAD

**Issue by plaindocs** [asciidoctor/asciidoctor.org#348]
Hi Guys,

Would be nice if `asciidoctor -h` told you what the available backends were, so I don't have to look it up separately.

**Comment by plaindocs** [comment]
Point me at the repo / file if you want a PR (no promises :-p)

**Comment by mojavelinux** [comment]
Great idea! Keep in mind, this will just be the out of the box list, as you can add a backend by putting a converter on the load path. However, we could leave a space for `*` or `other` so that users are prompted to this fact.

Here's the repo and file:

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/cli/options.rb#L46

Look at the doctype option to see how to add this information.

Cheers!

**Comment by mojavelinux** [comment]
Let's go ahead and create a mirror of this issue in that repository and link the two together (link just by mentioning in a comment).

**Comment by mojavelinux** [comment]
This was resolved upstream.
