### ISSUE TITLE
Colophon header level

### ISSUE THREAD

**Issue by plaindocs** [asciidoctor/asciidoctor.org#351]
In the docs http://asciidoctor.org/docs/user-manual/#doc-preamble the colophon is shown at level 2 (and not marked as a colophon). 

```
= Document Title

:numbered!:

== Colophon Section

== Another Colophon Section
```

but in the docs here http://asciidoctor.org/docs/user-manual/#user-colophon it is shown at level 1

```
[colophon]
= Colophon

The Asciidoctor Press, Ceres and Denver
```

Using this second usage (with asciidoctor-pdf) makes all of my chapters sub chapters of the colophon (which is not what I want).

If you let me know what the correct usage is I'll update the docs, or at least the user manual.

**Comment by mojavelinux** [comment]
This is one of those weird things inherited from AsciiDoc Python. For some reason, AsciiDoc Python allows special sections to be either level-0 (one equals sign) or level-1 (two equals signs). But it treats the both as level-1. However, it doesn't do it by changing the level in the AST, only in the output. Thus, you end up with strange results if you use level-0 and it's not the last section (it ends up with children it shouldn't have).

The best thing to do is to put the colophon at the correct level, which is level-1. I really don't understand why AsciiDoc Python added this quirky logic (which we've faithfully implemented). I have plans to fix this in the model. See https://github.com/asciidoctor/asciidoctor/issues/1261 and https://github.com/asciidoctor/asciidoctor/issues/1188.

**Comment by cemerick** [comment]
I'm afraid I've not been able to get a proper colophon outputted at all. This is sort of the endpoint of my experimentations:

```
:numbered!:
[colophon]
== {nbsp}
...
```

(`{nbsp}` because I don't want a section header for the colophon.) That section's content continues to be numbered, and placed before the table of contents (even if I use a `toc:[]` macro placed explicitly after the colophon section).

Any ideas?

**Comment by mojavelinux** [comment]
This is not well documented. The best I can do right now is give you an example:

```
= Multi-Part Book Example
Author Name <author@example.com>
:doctype: book
:sectnums:
:toc: macro
:preface-title: Preamble
:imagesdir: images

ifdef::basebackend-html[toc::[]]

This is the preamble.

[colophon]
= Example Colophon

Text at the beginning of a book describing facts about its production.

= The First Part of the Book

[partintro]
.Optional part introduction title
--
Optional part introduction goes here.
--

== The First Chapter

Chapters can be grouped by preceeding them with a level 0 Book Part title.

:sectnums!:

[appendix]
= Example Appendix

One or more optional appendixes go here at section level zero.
```

The colophon should not get numbered. Whether it shows up in the table of contents depends on the converter you are using. It will be included in the table of contents when using the html5 and pdf backends, but not when using a2x --fop or fopub.

**Comment by mojavelinux** [comment]
@plaindocs the colophon examples in the user manual that are not marked `[colophon]` are using the term "colophon" in the general sense (as a way of describing the example content, not the structural role of the section).

**Comment by cemerick** [comment]
Ech, two goofs in my comment/question:

1. I should have mentioned that (at least right now) I'm only outputting to PDF (via asciidoctor-pdf at the moment, though that may not last)
2. I'm actually expecting the colophon to come _before_ the ToC, not after (as it is currently). See page 3 in the PDF here, for example: http://cdn.oreilly.com/oreilly/booksamplers/9781449394707_sampler.pdf

Said differently, `[colophon]` doesn't appear to affect the following section at all. Sorry for botching the comment, and thanks for taking the time to respond.

**Comment by mojavelinux** [comment]
Asciidoctor PDF currently does not allow the TOC to be moved. That's an open issue. See https://github.com/asciidoctor/asciidoctor-pdf/issues/233.

**Comment by plaindocs** [comment]
"@plaindocs the colophon examples in the user manual that are not marked [colophon] are using the term "colophon" in the general sense (as a way of describing the example content, not the structural role of the section)."

hahaha, confusing much. I'll *try* to find time to update that section of the docs. Don't hold your breath though.

**Comment by jagdeepjain** [comment]
@cemerick @mojavelinux I have successfully placed colophon above table of content, I am using **asciidoctor-fopub **and after build you will see `component.xsl `under `build/fopub/docbook/fo/` folder. Search for first occurrence of `<xsl:template match="d:colophon"> `and update this to `<xsl:template match="d:colophon" mode="colophon">` and under your main .adoc file just include your colophon.adoc as the first include, build it and you will be good to have colophon above toc.

**Comment by jagdeepjain** [comment]
Now what I am looking for is how I can reduce the size of colophon text :) any pointers?

**Comment by mojavelinux** [comment]
Now you're venturing into the realm that is covered best by these SageHill DocBook customization guides. http://www.sagehill.net/docbookxsl/ReplaceTemplate.html

**Comment by mojavelinux** [comment]
The information discussed in this issue is now covered in the new docs. I'll explain where you can find it.

First, the page about the colophon specifically addresses when to choose a level-0 section (`=`) over a level-1 section (`==`). See https://docs.asciidoctor.org/asciidoc/latest/sections/colophon/ (hint: it's when you have a book with parts, called a multipart book).

The page about parts explains in more detail why this distinction is necessary. That section includes a simplified variation of the example I shared above. See https://docs.asciidoctor.org/asciidoc/latest/sections/parts/#special-sections-as-part-siblings

It's also possible to hide the title of a special section when generating DocBook or PDF. (For PDF, the feature won't be available until Asciidoctor PDF 2 is (pre)released). See https://docs.asciidoctor.org/asciidoc/latest/sections/special-section-titles/

And since Asciidoctor 2, special sections are not numbered by default. See https://docs.asciidoctor.org/asciidoc/latest/sections/special-section-numbers/

If you see anything else that needs to be improved in the docs, please click "Edit this Page" and either submit a proposal or switch to the Issues tab and file an issue.
