### ISSUE TITLE
toc-class attribute not documented

### ISSUE THREAD

**Issue by DavidGamba** [asciidoctor/asciidoctor.org#379]

**Comment by jaredmorgs** [comment]
@mojavelinux what does this attribute do?

**Comment by mojavelinux** [comment]
It allows you to set the CSS class that is applied to the table of contents in the HTML output.

However, there is one caveat at the moment. Applying your own class may inadvertently disable built-in styles that are needed to properly display the table of contents, so you should only use it if you really know what you are doing.

This is definitely one of those things that we implemented from AsciiDoc Python, but there are better ways to solve the problem in Asciidoctor, such as using a custom template (since you likely want to change more than just the CSS class).

**Comment by mojavelinux** [comment]
The toc-class attribute is now mentioned on the TOC reference page. See https://docs.asciidoctor.org/asciidoc/latest/toc/toc-ref/ If you'd think there should be a dedicated page for it, please open an issue in the linked repository.
