### ISSUE TITLE
Create a detailed Theme Creation Howto Guide

### ISSUE THREAD

**Issue by andrew-simmons** [asciidoctor/asciidoctor.org#388]
The current theme documentation page _[Produce Custom Themes Using the Asciidoctor Stylesheet Factory](http://asciidoctor.org/docs/produce-custom-themes-using-asciidoctor-stylesheet-factory/)_ feels very spartan and is focused more on applying available themes than on creating new ones.  A walk through or a more in depth guide explaining how themes work in Asciidoctor would be helpful.

**Comment by mojavelinux** [comment]
I totally agree.

I do want to mention that I'd like to complete the upgrade to Foundation 5 and the refactoring before writing the guide because the current way of creating themes just isn't right yet...and will change. See the following issues:

* https://github.com/asciidoctor/asciidoctor-stylesheet-factory/pull/23
* https://github.com/asciidoctor/asciidoctor-stylesheet-factory/pull/2

**Comment by mojavelinux** [comment]
The stylesheet factory is no longer maintained and the default stylesheet has been pulled into the core repository. We're now deferring to the asciidoctor-skins project as an example of how to create themes. You also have the option of downloading the unprocessed source of the default stylesheet and customizing it to suit your needs. I've redirected the aforementioned page to the page in the new documentation site that covers this topic.

One of the goals of the modern HTML converter (currently under development) will be to provide a style guide for how to write a custom stylesheet (in plain CSS) to style and theme the HTML. See https://github.com/asciidoctor/asciidoctor/issues/4171. That's where we'll focus our attention.
