### ISSUE TITLE
Documentation needs update in asciidoctor.org user manual PDF section?

### ISSUE THREAD

**Issue by wolandscat** [asciidoctor/asciidoctor.org#400]
The information [here](http://asciidoctor.org/docs/user-manual/#pdfs) doesn't mention asciidoctor-pdf or [PDF theming](http://gist.asciidoctor.org/?github-asciidoctor%2Fasciidoctor-pdf%2F%2Fdocs%2Ftheming-guide.adoc).

**Comment by mojavelinux** [comment]
This is related to our overall information architecture discussion. Currently, information from the projects is not pulled into the website automatically. It's synced manually (and quite painfully). We're currently working on getting a pipeline setup so that these guides are sourced directly from the project, removing any discrepancies.

...I'm also not promoting the theming engine heavily until we reach beta because I'm likely going to have to change some of the key names as part of the fix for https://github.com/asciidoctor/asciidoctor-pdf/issues/132.

**Comment by wolandscat** [comment]
I'm happy to keep being the test rat:)

**Comment by jaredmorgs** [comment]
In the short term, I've created #430 which mentions asciidoctor-pdf.

It doesn't include PDF themeing.

**Comment by mojavelinux** [comment]
:+1:

**Comment by jaredmorgs** [comment]
This issue is kind of partially done with my PR, except for PDF theming. I would imagine that PDF theming is going to be done as part of the larger asciidoctor-pdf work, so is this issue a candidate for closure @mojavelinux ?

**Comment by wolandscat** [comment]
FWIW I think making it separate is reasonable.

**Comment by mojavelinux** [comment]
We have a link to the theming guide in that section, so I think that is sufficient. Since that guide is still very much in flux, I don't think it's ready to integrate into asciidoctor.org yet.
