### ISSUE TITLE
Document the preamble toc option

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#418]
The preamble toc option is mentioned, but never explained. It should have a section just like the macro option.

**Comment by rockyallen** [comment]
There is already a section on preamble, but it is confused at the moment with toc-placement:
````
Asciidoctor also has a toc-placement attribute, that when set with a value of preamble places the TOC below the preamble. You do not need to include the toc::[] block macro in the document when using the preamble value.

If you set toc-placement but don’t assign it a value, the TOC will be placed in the document’s header by default.
	The toc-placement and toc-position attributes are mutually exclusive. 
````
but immediately after, it says that toc-placement and toc-position are set _from_ the toc value, and should be treated as read-only, which is inconsistent with the first statement.

Since toc can do it all, I suggest replacing toc-placement by toc=preamble in the above quote, deleting the discussion of toc-placement and toc-position entirely from this section, and marking them as deprecated in the attributes appendix.

In the summary table, since they are marked as r/o, the how to set them examples should be removed.

**Comment by mojavelinux** [comment]
> Since toc can do it all, I suggest replacing toc-placement by toc=preamble in the above quote, deleting the discussion of toc-placement and toc-position entirely from this section, and marking them as deprecated in the attributes appendix.

I agree 100%. We should remove mention of the low-level attributes, toc-placement and toc-position, (which may eventually go away) and only mention the `toc` attribute and its capabilities.

**Comment by rockyallen** [comment]
See PR #623
