### ISSUE TITLE
"Compared to Markdown" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#435]
http://asciidoctor.org/docs/user-manual/#compared-to-markdown is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by mojavelinux** [comment]
Here's some more good raw material on the subject:

https://github.com/graphitefriction/oscon-2013-docs-workshop/blob/master/convert-markdown-to-asciidoc.adoc

**Comment by mojavelinux** [comment]
When this page goes live, post a link to it on the following issue in the GitLab CE project.

https://gitlab.com/gitlab-org/gitlab-ce/issues/10778

**Comment by mojavelinux** [comment]
Here are some opinion pieces on the subject we might want to link to:

* https://medium.com/@bbirdiman/markdown-considered-harmful-495ccfe24a52
* http://ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/

**Comment by mojavelinux** [comment]
The first draft is in! Let's track revisions in dedicated issues.

**Comment by mojavelinux** [comment]
I posted a link to the section in the comments of the referenced GitLab issue.

**Comment by nancym** [comment]
Under the table *1.5.1. A basic comparison by example*, it says:

    * Asciidoctor also supports the Markdown syntax for this language feature.

The asterisks signifying this were hard for me to notice. Here are a few suggestions:

1. Because asterisks have special meaning in a lot of Asciidoc syntax, use a different character to signify this.
2. Put this character at the beginning of the **Language Feature** text rather than the end.
3. Maybe color this character so it stands out even more.

This table is very useful and I've printed it out and use it when writing in Markdown (e.g. now in this GitHub issue) and when I'm writing AsciiDoc. It's confusing to be bilingual with these two languages!

**Comment by mojavelinux** [comment]
Please open a separate issue if you'd like to propose improvements to this section.
