### ISSUE TITLE
Asciidoctor vs AsciiDoc section needs links to AsciiDoc original docs.

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#439]
I saw one of my devs use the [line-through] attribute today to strikethrough some text. Not having seen this one before, I decided to investigate what this attribute was for. 

It appeared in the http://asciidoctor.org/docs/user-manual/#asciidoctor-vs-asciidoc section, but that was the only mention of the attribute.

I did an internet search and found that the attribute is part of vanilla AsciiDoc, and is mentioned at http://www.methods.co.nz/asciidoc/chunked/ch10.html

The table doesn't link off to the sections for which the attributes are mentioned. I don't want to suggest we "re-write the internet" and duplicate content, but we should consider linking to relevant vanilla AsciiDoc sections if we are not going to document them explicitly.

**Comment by mojavelinux** [comment]
I'd rather not link to the AsciiDoc Python user guide. Our objective here is to replace the need for that guide. It is very out of date and potentially a source for major confusion.

Asciidoctor supports all the features of AsciiDoc Python, except for the templating / configuration file mechanism (since we have our own way). Thus, we support the line-through as well. (Technically, it's a feature of the default CSS more than anything else).

**Comment by mojavelinux** [comment]
To state it another way, we want Asciidoctor to be the canonical source of information for AsciiDoc.

The only reason we mention AsciiDoc Python features is for migration purposes and thus should be framed that way.

**Comment by jaredmorgs** [comment]
I agree with Asciidoctor becoming the canonical source of documentation for
AsciiDoc.

Is there a better solution for including strikethrough in AsciiDoctor than
using [line-through].

I know markdown just uses -strikethrough- from memory. There are no results
for strikethrough in the User Guide.

My suggestion would be to include a mention for Strikethrough in the TOC
(so google crawls it) and then suggest that [line-through] is used and
include how to do it from the methods guide.

On Wed, 16 Dec 2015 at 10:50 Dan Allen <notifications@github.com> wrote:

> To state it another way, we want Asciidoctor to be the canonical source of
> information for AsciiDoc.
>
> The only reason we mention AsciiDoc Python features is for migration
> purposes and thus should be framed that way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/439#issuecomment-164947912>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
Yes, there's an open issue. #224.

**Comment by mojavelinux** [comment]
> My suggestion would be to include a mention for Strikethrough in the TOC

There's a whole family of these inline formatting classes, so the TOC section should be something like "other built-in text formatting".

Here's the list:

* big
* small
* underline
* overline
* line-through
* numerous colors (see https://github.com/asciidoctor/asciidoctor/blob/master/data/stylesheets/asciidoctor-default.css#L323-L354)

I've considered removing the colors because I really don't think it is a good idea to be providing that by default. Maybe something like "primary" and "secondary", but not specific colors.

**Comment by mojavelinux** [comment]
> Is there a better solution for including strikethrough in AsciiDoctor than using [line-through].

This is the correct way. It is written as `[.line-through]#strike this text#`.

These supplemental built-in roles are now covered on the following page: https://docs.asciidoctor.org/asciidoc/latest/text/text-span-built-in-roles/#built-in-roles-for-text. If you search for "strikethrough" on the docs site, it turns up a result for this section.
