### ISSUE TITLE
Update the Editing with Live Preview doc

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#48]
Update the Editing with Live Preview docs to feature all recommended approaches to editing AsciiDoc.

This page should include:
- DoctorFX / Doctorpad
- Guard and LiveReload plugins
- Gedit
- Sublime Text editor

And perhaps others as needed.

**Comment by jaredmorgs** [comment]
Some related issues: 

* #450 is for Guard/LiveReload plugins discussion.
* DoctorFX is mentioned in [this google plus post](https://plus.google.com/114112334290393746697/posts/jb8WaxCT55V) and is hosted [here](https://github.com/glaforge/doctorpad) is not updated since 2013.
* [Redoculous](http://www.ocpsoft.org/redoculous/) is still up, but no idea of source code location. 
* Gedit (there's a live preview for this?)
* [Sublime Text 3](https://github.com/asciidoctor/sublimetext-asciidoc) is nice and fresh.

I know that there are some sections in the User Guide that could be filled with shoutouts to the Sublime editor and maybe some of the more actively maintained projects.

**Comment by mojavelinux** [comment]
We should drop mention of DoctorFX in favor of AsciidocFX.

The source for redoculous is here: https://github.com/ocpsoft/redoculous

Gedit does not have a live preview. Frankly I think there are better options because it's super difficult to get updated. Maybe just a footnote worth of mention.

I'm not big on shouting out Sublime because it is proprietary software. We can mention the plugin, of course. Otherwise, there are plenty of open source options available.

**Comment by jaredmorgs** [comment]
Are we talking about http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/ as the target for these changes?

That part of the docs seems to be pretty comprehensive already.

I think some changes above need to be made in http://asciidoctor.org/docs/user-manual/#text-editor.

Thoughts, @mojavelinux ?

**Comment by mojavelinux** [comment]
I think docs about tools should be on a separate page (and not directly in the user manual). Therefore, I'm okay with the reference from the user manual to this page. We could certainly update the summary as it was written before many of the tools existed.

I don't particularly like the current "Editing AsciiDoc with Live Preview" document for a couple of reasons:

1. It's not a great title. We need something that is about editing in general. The live preview is but one feature of editing. And in some case, we're only previewing and not editing.
2. We shouldn't cover the guard plugin since it's not maintained (and not even released). We should focus on the IDE and browser extensions instead.
3. The document needs to be more approachable with a goal/solution format. Something like "You've come here because you want to either preview or edit an AsciiDoc file. You've come to the right place. In this document, we'll give you a tour of the tools available in the ecosystem and make some recommendations based on the use case that you have." (In other words, I think it needs a better lead in and a better journey).

**Comment by gmarpons** [comment]
After checking Atom, Brackets and Visual Studio Code (all of them open source editors with easy-to-install plugins for Asciidoc preview), the one I found to give the most well-rounded experience (by a small margin) is Visual Studio Code. 

I detail my settings here: https://docs.decidim.org/docs-authoring/en/prerequisites/#install-editor.

The features that convinced me:

- Very easy to install, well-maintained Asciidoc plugin. The preview scrolls with the edition window.
- Can switch between integrated JS previewer and system-installed, configurable `asciidoctor` command (useful for realistic visualization in the presence of pre-processor directives, images, etc).
- Easy to install, well-integrated spell checker (cross-platform, many languages available).

With Atom you can get the same features, but you need a grater number of plugins and set up spell checking is more difficult depending on the OS.

**Comment by settermjd** [comment]
I'm happy to contribute to this. @mojavelinux, I think you referenced some content that I wrote late last year, that might be a good fit.

**Comment by john-cj** [comment]
> 2\. We shouldn't cover the guard plugin since it's not maintained (and not even released). We should focus on the IDE and browser extensions instead.

It is worthwhile to mention that there are _two_ Guard plugins.

* https://github.com/guard/guard-shell (0.0.7, not updated from 8 Dec 2014)
* https://github.com/asciidoctor/guard-asciidoc (0.0.5, not updated from 29 Oct 2015)

As I understand, guard-asciidoc, despite being slightly "newer", is less powerful (and therefore is not mentioned in the article at all). E.g. it doesn't have the stylesheet option.

**Comment by john-cj** [comment]
I have created a small GUI script as a possible replacement of Guard: https://github.com/john-cj/Asciidoctor.ahk

**Comment by sturtison** [comment]
I've found that on the MacBook using Visual Studio Code (VSCode) with the Asciidoc plugin from João Pinto to be extremely easy to install and be productive quickly. This is an added bonus due to VSCode becoming very widely used. I've also tried Atom like @gmarpons and come to the same conclusion.

I agree with the discussions about the documentation in general and the need for a perhaps a more general "editing" page as discussed by @mojavelinux [previously](https://github.com/asciidoctor/asciidoctor.org/issues/48#issuecomment-184559712) in this same thread.

Would a simple update to show that the VSCode editor is useful, in the same line as Brackets is described be useful? If so, I've made a pull request to describe such an addition.

**Comment by mojavelinux** [comment]
This issue has morphed into a general discussion and, while useful, is no longer actionable. The old page at https://asciidoctor.org/docs/editing-asciidoc-with-live-preview now redirects to the "AsciiDoc Tooling" page in the new Asciidoctor docs. If you'd like to see an addition or revision made to that page, please click "Edit this Page" and propose a change. If you'd like to see a new page that is dedicated to a single tool, please submit a PR to add a new page under "AsciiDoc Tooling".

Ideally, the information in the Asciidoctor core docs should link out to tutorials maintained by the respective project. I'm also open to link to contributed articles. Putting those detailed docs in the Asciidoctor core docs makes them harder to keep updated.
