### ISSUE TITLE
Merge tables "Built-in entity attributes" and "Built-in literal attributes" in appendix B

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#495]
...and give the numeric value in the second column in both cases.
Reason: The user does not need to know how they are defined internally, just what to type to get a particular character. Putting them in separate tables invites the question why?
Or, if there is a functional difference it should be explained.

**Comment by mojavelinux** [comment]
They are different, but they don't necessarily need to be in separate tables. The "entity attributes" emit an XML entity character (e.g., `&#34`) whereas the "literal attributes" emit a string of normal character (e.g., `<`). Having said that, I think this is easily understood by the example value.

I do think it is important to show which character goes into the document and how it looks when it is rendered. This is important information for people using it. Having said that, I think we can make better column names:

* Attribute reference
* Resolved value
* How it appears when viewed

wdyt?

**Comment by rockyallen** [comment]
How about:
1. Name columns: Attribute reference, Replacement text [1], How it appears when converted
2. Merge rows and put in alphabetical order by attribute name
3 Rename table to "Built-in attributes for character replacements"
4. Add note "[1] Replacement text can be a literal string, or a numeric entity as shown. The effect is the same however it is defined."
?

**Comment by mojavelinux** [comment]
> 1) Name columns: Attribute reference, Replacement text [1], How it appears when converted

To make it more brief, how about simply "Appearance" for the last column?

> 2) ...

:+1: 

> 3) Rename table to "Built-in attributes for character replacements"

How about "Predefined attributes for character replacements". I like "predefined" because these are really "defined for convenience" since they are effectively the same as the author defining these explicitly. They don't otherwise affect processing.

> 4) Add note "[1] Replacement text can be a literal string, or a numeric entity as shown. The effect is the same however it is defined."

I wouldn't go so far to say that the effect is the same since there are reasons why the replacement is the way it is. What I'd say is that the replacement text is selected strategically to have the least impact on processing. The goal is to slip the content into the output without being misinterpreted (either by the processor or the viewer/browser).
