### ISSUE TITLE
Include directive

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#506]
Section is an excellent reference, in that it gives all the information you could possibly need, but:

* For an essential topic, it is introduced quite late in the guide (section 50)
* It dives straight into the detail without demonstrating how it 'just works' for the most common use case of a document divided into chapter files
* It references the Asciidoc manual

Can I suggest a minor reorganization to remove the link, give a gentler introduction, and cover the common use cases first?

**Comment by mojavelinux** [comment]
Absolutely!

It seems like it would fit well under the "Building Your Content" part, since it directly relates to the building/assembly aspect. Perhaps after (or before) "Cross references". The pending section on Preprocessor conditionals should be a direct neighbor of this section since they go hand-in-hand. (See #283).

I think that the first subsection of "Include directive" should be "Partitioning chapters", as you have hinted. There's a partial example at the top of the section, but it's not explicit and lacks detail.

For context, the section you are referring to is http://asciidoctor.org/docs/user-manual/#include-directive.

**Comment by mojavelinux** [comment]
(In general, the sections in Building Your Content" could probably stand to be rearranged.)

**Comment by mojavelinux** [comment]
I'm really happy with the improvements to the Include Directive section. I think the information is much clearer and more complete now. If you see room for further refinements, don't hesitate to propose them!

**Comment by rockyallen** [comment]
Thanks. And I like your refinements - reads much more professionally now!

**Comment by mojavelinux** [comment]
I couldn't have done it without you giving me such a solid starting point. Teamwork!
