### ISSUE TITLE
Explain counter attributes better

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#561]
Currently only an example with no explanation. These notes are based on testing with 1.5.4 but are not all required.

Any document attribute can be used as a counter, but it is usual to use a special syntax to define them:

{counter:item_number:9} 

sets a document attribute item_number and assigns it value 9, then references it, ie it is shorthand for:

:item_number: 9
{item_number}

The initial value of the counter should[1] be a decimal integer (1 or more digits), single lower case letter, or single upper case letter.

If the initial value is not specified, the initial value is 1. Ie if item_number is not already set, {counter:item_number} is shorthand for

:item_number: 1
{item_number}

But if item_number is already set, the same expression {counter:item_number} increments the attribute value then references it.

"increment" means add 1 if the current value is an integer, or choose the next letter of the (ASCII) alphabet if it is anything else.
Therefore the number sequence runs 1,2,3....999....
but the letter sequence runs a,b,c,...x,y,z,{,|... or A,B,C,...,X,Y,Z,[,\... so isn't useful for more than 26 items.

{counter2:item_number} increments the attribute value, but does not reference it.

[1] It is not an error to have an initial value that does not match this, but the result will not be useful: for example the sequence starting "frogs" is "frogs","g","h"...

**Comment by rockyallen** [comment]
Oops - just noticed this is a duplicate of #550.

**Comment by mojavelinux** [comment]
This is great content, Rocky.

I think it may flow better if we start out by showing the example of the default initial value, then explain that the initial value can be customized, but only if the attribute is not previous set.

I'm thinking something like this:

--

Another use of a document attribute is for maintaining a counter. The value of the counter may be an integer or a letter (i.e., a single lowercase or uppercase Latin character).

To initialize a counter, you add the prefix \`counter:` to the name of the attribute in an attribute reference:

{counter:item_number}

This special attribute reference assigns an initial value to the attribute and then references it (i.e., leaves behind the value).
The default initial value is 1.

The counter attribute reference shown above is effectively the same as:

:item_number: 1
{item_number}

If you want to define or increment a counter attribute, but not reference it, you can use the \`counter2` prefix instead:

{counter2:item_number}

You can specify an initial value if you want to start the counter at a value other than 1.
This is most often used if you want the counter to be a letter.

{counter:item_number:A}

This counter attribute reference is effectively the same as:

:item_number: A
{item_number}

The initial value is only used if the attribute is not already set by a counter attribute reference.
Otherwise, the initial value is ignored.

You may be wondering when the counting part comes in.
In other words, when does the value get incremented?
The answer is in subsequent uses.

The value of the counter attribute is incremented each subsequent time the attribute is referenced as a counter attribute.
For example, the following AsciiDoc:

[source,asciidoc]
\* {counter:item_number:A}
\* {counter:item_number}
\* {counter:item_number}

or

[source,asciidoc]
\* {counter:item_number:A}
\* {counter:item_number:A}
\* {counter:item_number:A}

outputs the following:

\* A
\* B
\* C

You can reset the value of a counter using an attribute entry that unsets the attribute:

:!item_number:

It's important to note that the counter should only be used for simple cases.
Due to the way Asciidoctor processes the document, you may find that the counter behaves unexpectedly if you try to use it for complex procedures, such as for cross references and labels.

**Comment by mojavelinux** [comment]
@rockyallen, if this looks good, would you like to do the honors of converting this content to a pull request?

**Comment by rockyallen** [comment]
(How do I get a happy face smiley?)
Some minor quibbles: I hesitate to link them so strongly to document attributes: the explanation is just as clear if they are described simply as counters, and people won't then be led into my error, and making the warning unnecessary.
Also the examples would be better as inlines so people don't conflate them with numbered lists.
I will have go and and you can see what you think.

**Comment by mojavelinux** [comment]
> I hesitate to link them so strongly to document attributes: the explanation is just as clear if they are described simply as counters

I think we should simply say that an attribute entry can be used to reset the counter and leave it at that.

**Comment by rockyallen** [comment]
See PR.
Is it possible to allow {counter:name:value} to be used anywhere? 
Feels more logical, and aligns with user expectations.

**Comment by mojavelinux** [comment]
> Is it possible to allow {counter:name:value} to be used anywhere? 

It can be used anywhere an attribute reference can be used. Allowing it anywhere else would break fundamental assumptions in Asciidoctor.

**Comment by mojavelinux** [comment]
Merged as 531f83882a280bf1db7b762e74e9706fd16c19d5 with additional revision in 5b5d38860dfcf17d01b01149d375673fcf959bd2.
