### ISSUE TITLE
Clarify when replacements are used and how to escape them

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#568]
ref https://github.com/asciidoctor/asciidoctor/issues/1717

Add note to 40.4: "In most cases, replacements can be escaped by adding a leading \ character (e.g., \--)" [although I tested all of them and didn't find any exceptions]

Add note in table cell for --: "Only replaced if it is a word, ie surrounded by white space, line start, or line end." [Why? Seems an arbitrary decision - feels more like a bug]

**Comment by mojavelinux** [comment]
> [although I tested all of them and didn't find any exceptions]

I'll admit the exceptions are extremely esoteric, so much so that it may not even be worth mentioning. Since the inline parser is still regexp based, it's highly dependent on other content on the same line/paragraph. In other words, you can confuse it if you try hard enough.

> "Only replaced if it is a word, ie surrounded by white space, line start, or line end." [Why? Seems an arbitrary decision - feels more like a bug]

The implementation is intentional. What we're really questioning is the intent. That traces back to a decision in AsciiDoc Python. I think the idea was to only catch cases where dashes are permitted according to writing style manuals (e.g., Chicago, Oxford) to avoid unexpected replacements. However, my guess is that rules in AsciiDoc are not all that accurate.

Either way, that's a decision for core.
