### ISSUE TITLE
Links won't work in the footer

### ISSUE THREAD

**Issue by PauloFrancaLacerda** [asciidoctor/asciidoctor.org#624]
Hi, there.
I'm new to Asciidoctor but I'm loving it already.
I tried to express that by adding a link to the Asciidoctor site in the footer, but it didn't work.

Here it is:
`:last-update-label: Generated with http://asciidoctor.org[Asciidoctor] v{asciidoctor-version} on`

The `{asciidoctor-version}` attr expands normally, though.
The same link works everywhere in the doc, except in the footer.
Is this by design?

Thanks in advance.
`[Asciidoctor 1.5.5 on Ruby 2.2.4p230, Windows 7 32-bit]`

**Comment by mojavelinux** [comment]
By default, only special characters and attribute references are resolved in an attribute entry (i.e., variable assignment). If you want to change the substitutions that are applied, you need to use a inline pass macro. You're in luck because we just revised the section in the manual on this topic.

See http://asciidoctor.org/docs/user-manual/#altering-attribute-entry-substitutions

**Comment by mojavelinux** [comment]
I believe this is now covered in the documentation. Please reopen if that's not the case.
