### ISSUE TITLE
The documents of the other projects could be included?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor.org#639]
I find that the document of the asciidoctor-diagram is included into the site. 

But the documents of the other projects are not included.

**The documents of the other projects could be included?** It reduces duplication of document.

**Comment by mojavelinux** [comment]
Yes, we are migrating towards that. We just have not completed the effort yet. One of the reasons for the delay is that the documents need to be checked for divergence (in some cases, they were being edited in two places). Once we are sure we've merged all the content, then we can switch to including the document instead of duplicating it.

**Comment by mojavelinux** [comment]
See https://docs.asciidoctor.org/diagram-extension/latest/
