### ISSUE TITLE
No alternatives to low contrast captchas on email registration form

### ISSUE THREAD

**Issue by janicecmt** [asciidoctor/asciidoctor.org#641]
The captchas used on the registration page for the email list are extremely low contrast - the background and foreground are basically indistinguishable. However, there is no alternative option. Even captchas with high contrast between the foreground and background (i.e. that are much easier to read) typically offer either an audio alternative or another way to bypass the captcha for folks who have difficulty parsing the default option.

**Comment by mojavelinux** [comment]
It appears like Nabble has since implemented a new captcha system which offers more options for usability. It's also possible to subscribe to the list via e-mail without registering which does not go through the captcha flow (see http://discuss.asciidoctor.org/template/NamlServlet.jtp?macro=subscribe&node=1).
