### ISSUE TITLE
Document \t for table cell separators.

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#684]
At the same time, clarify the difference between Asciidoctor processing and CSV processing.

I think:
- |=== or format=psv set Asciidoctor processing and the default separator = |
- ,=== or format=csv set CSV processing, and the default separator = ,
- format=dsv is the same as format=csv, separator=:
- format=tsv is the same as format=csv, separator=\t
- ,=== with format=psv feels like it should be an error, but is actually results in psv.

"CSV" processing is 1 row per line, separators _between_ fields, quoting using "", and no cell-level formatting. Cell content can be Asciidoc if it is in the source file or included:: from an Asciidoctor file type (but not any other extension). So you can have Asciidoc content in CSV files, you just need to rename them to .adoc.
Should also explain what it does If content is not strict RFC 4180, ie blank lines, extra spaces, ragged rows, and  embedded newlines in quoted values.

**Comment by mojavelinux** [comment]
> Cell content can be Asciidoc if it is in the source file or included:: from an Asciidoctor file type (but not any other extension).

In fact, it's not related to whether you use the include directive or not. The include directive gets expanded before the parser comes along, so as far as the parser is concerned, it doesn't even see the include directive. It only sees the content.

All table cells support inline AsciiDoc (unless limited by the cell style). When we say "AsciiDoc table cell", it means the cell can have block content. However, block content doesn't really fit with CSV formatting (without doing some serious back bending).

The reason CSV and DSV formatted data don't support cell styles is because there's no place in the data to declare it. But they inherit the cell style defined for the column.
