### ISSUE TITLE
Examples for unconstrained formatting are contradictory

### ISSUE THREAD

**Issue by tribut** [asciidoctor/asciidoctor.org#686]
The section [When should I use unconstrained quotes?](https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/formatting-marks.adoc#when-should-i-use-unconstrained-quotes) is not clear to me, especially the two examples

 * `–**2016**`: *Unconstrained, because of the “–” to the left of the emboldened number.*
  However, “–” is not a letter, number, underscore, colon or semi-colon. So according to the rules, unconstrained formatting should not be needed.
 * `*2016*–`: *Constrained, because the “&” is not a letter, number, underscore, or semi-colon.*
  There is no ampersand there. Maybe that's just a typo?

**Comment by mojavelinux** [comment]
It's important to remember that the dash glyph is represented as a character reference. Therefore, what the parser sees is not what you see. What the parser sees is `&ndash;`. That's where the semi-colon and & come from.

The problem with this example is that you are seeing the converted result, not the source. It needs to be fixed so that you can see the source AsciiDoc. Then it would make sense.

**Comment by tribut** [comment]
Right, I submitted a PR accordingly.

**Comment by mojavelinux** [comment]
This should make *a lot* more sense. http://localhost:4242/docs/user-manual/#constrained-or-unconstrained

**Comment by mojavelinux** [comment]
Uh oh, looks like our efforts crossed paths. Can you review what I wrote and see if you still want to add to it?

**Comment by mojavelinux** [comment]
(give it a moment to refresh)

**Comment by mojavelinux** [comment]
It's ready now.

**Comment by tribut** [comment]
Heh, should have expected that. Just one little thing I'm missing from my changes.
