### ISSUE TITLE
The dropping-the-principle-text example on writer's guide doesn't match the behavior of asciidoctor 1.5.6.1

### ISSUE THREAD

**Issue by crocket** [asciidoctor/asciidoctor.org#695]
## What I expected

![2017-08-04_fri_12 19 09](https://user-images.githubusercontent.com/748856/28968372-9f42fe8a-795a-11e7-9ed2-e528269db8d0.png)

## What I got from asciidoctor 1.5.6.1 via Visual Studio Code

![2017-08-04_fri_12 20 40](https://user-images.githubusercontent.com/748856/28968608-c9cde452-795b-11e7-96d2-45bc60fda51e.png)

**Comment by mojavelinux** [comment]
This turned out to be a stylesheet issue on the website. When the nowrap option is applied to a listing block that occurs as the first block in a list with no text, the block jumps below the number.

It's technically still a problem in the default stylesheet. I don't actually know how to fix it. What I did on the website is disable the nowrap option for that example.

See http://asciidoctor.org/docs/user-manual/#dropping-the-principal-text.
