### ISSUE TITLE
On website, Sec. 22's backticks operating as in AsciiDoc, not AsciiDoctor

### ISSUE THREAD

**Issue by andrewcarver** [asciidoctor/asciidoctor.org#737]
Weirdness is rampant in Sec. 22 of the User Manual--on the website, but not (apparently) in GitHub.

Backticks, of whatever AsciiDoctor deployment, are being handled as if it were all in AsciiDoc, not AsciiDoctor (!!):

- many attribute references that were surrounded with backticks have ended up not having substitution done on them
- backticks intended as part of curved-quote marks are being treated as monospace-and-passthru marks, again as in AsciiDoc

**Comment by mojavelinux** [comment]
Ooops!! My mistake. I was cleaning up the compat mode settings and I got confused. We set the compat-mode by default when generating the site since some of the documents still haven't been migrated. So we still have to unset it for any document which is not written in compat mode.

What I need to do is the opposite. I need to mark all remaining legacy documents with compat-mode so that we can then remove it from the site configuration.

**Comment by mojavelinux** [comment]
I reverted the change here: 2af0a3047ca528f5f2886c012930de35ad49fe94

I'll now apply the opposite logic.

**Comment by mojavelinux** [comment]
I've made the switch. Now, only pages which are actually using compat mode are marked as such. (And eventually, any document inside docs/ should not need compat mode to be on).

**Comment by mojavelinux** [comment]
There are only two docs remaining in docs/ that use compat-mode (not counting migration.adoc which requires it).

**Comment by mojavelinux** [comment]
Thanks for catching!

**Comment by andrewcarver** [comment]
You're welcome!

**Comment by andrewcarver** [comment]
Thanks for fixing!!
