### ISSUE TITLE
Is there any online platform supporting asciidoc fully?

### ISSUE THREAD

**Issue by webia1** [asciidoctor/asciidoctor.org#754]
I am writing a scientific document with many mathematics formulae, source code, etc. in a team and we want to exchange the document parts, include sections etc. online. 

Is there any online platform supporting asciidoc fully? Github is would be our choice, but it lacks important features.

Could you help me further? Many thanks! :christmas_tree:

**Comment by mojavelinux** [comment]
The most complete support I know of at the moment is GitLab. It supports many features that GitHub does not, most notably the include directive, font-based icons, diagrams, and STEM. See https://docs.gitlab.com/ee/user/asciidoc.html Since GitLab is open source, it's possible for us, as a community, to contribute improvements.

In the future, please ask general questions like this in the community chat at https://asciidoctor.zulipchat.com. Thanks!
