### ISSUE TITLE
Support terminal (color ascii art) target

### ISSUE THREAD

**Issue by Siltaar** [asciidoctor/asciidoctor.org#803]
Hi,

In order to create terminal readable websites such as : wttr.in ; cheat.sh ; rate.sx …
https://github.com/chubin/wttr.in

AsciiDoctor could be able to produce terminal colored texts instead of HTML ones… (a bit like the man page target).

**Comment by mojavelinux** [comment]
I like the idea. You'd want to create a dedicated converter. You could probably draw on the manpage converter for inspiration.

Since this is just a proposed idea, and not part of the website, I don't think this belongs in an issue tracker. If you're looking for help, I suggest floating the idea in one of the following places:

* http://discuss.asciidoctor.org
* https://gitter.im/asciidoctor/asciidoctor

If you have a docs suggestion, raise it here. If you run into problems creating the converter code, open an issue in https://github.com/asciidoctor/asciidoctor.
