### ISSUE TITLE
Cube root in stem?

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor.org#844]
Hello!

```
:stem: latexmath

stem:[sqrt[3]{x}]
```

There are square brackets in inline stem. How to display cube root in inline stem?

Andrey.

**Comment by sindzicat** [comment]
OMG, guys! I solved it!

```
:stem: latexmath

stem:[+++\sqrt[3]{x}+++]
```

Please, add such moment in your docs! :memo:

**Comment by mojavelinux** [comment]
This is written more simply as:

```
stem:[\sqrt[3\]{x}]
```

The `]` in the equation has to be escaped with a backslash since it's inside an AsciiDoc macro. The backslash in front of `sqrt` is required by LaTeX.

If you'd like to see this example added to the docs (here: https://asciidoctor.org/docs/user-manual/#stem-in), feel free to send a pull request. :beers:

**Comment by sindzicat** [comment]
Thanks! Your way is better!

**Comment by sindzicat** [comment]
Thanks)

**Comment by mojavelinux** [comment]
Example added.
