### ISSUE TITLE
Add links from the glossary to the detailed sections

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#851]
I think they would help. Is there any reason not to?

**Comment by mojavelinux** [comment]
FYI, we're completely overhauling and reorganizing the docs right now to be based on Antora. That's why we aren't really touching this site. Under the new structure, there will be a ton more references crisscrossing the site, because Antora makes that possible. Here's where that's happening: https://github.com/asciidoctor/asciidoctor.org/issues/851 Except some big pushes in the next few days.

**Comment by rockyallen** [comment]
So don't raise any PRs until after the change?

**Comment by mojavelinux** [comment]
PRs for content are fine because I can port the changes over. But moving files around would make merging prohibitively difficult.

**Comment by mojavelinux** [comment]
The docs are now open for revision at https://docs.asciidoctor.org.

I've given this some thought and I don't think it's very standard practice to add links from the glossary. It's hard to know the best place to send the user when they are looking at the glossary. Some terms may have clear targets, others may not. I'd rather keep the glossary as the destination rather than the source of references.
