### ISSUE TITLE
[user-manual] Cross reference sample wrong

### ISSUE THREAD

**Issue by mick62** [asciidoctor/asciidoctor.org#928]
Chapter 1.5.3 of "user-manual"

It seems that the sample for "Cross reference":

See <<_usage>>.

== Usage

wont work (w/o an anchor definition).
Also the following sample for "Block ID / anchor":

[#usage]
== Usage

is not consistent with this cross reference sample.

Another small inconsistency is in the "File link" samples:

"site.url" vs. "site-url".

In the "URI reference" samples for markdown and asciidoc the lines should have the same order.

The foot note reference (*) should be applied where ever possible features in the table.
* Asciidoctor also supports the Markdown syntax for this language feature.

**Comment by mojavelinux** [comment]
The documentation for AsciiDoc and Asciidoctor has been rewritten and is now published at https://docs.asciidoctor.org. As part of this migration, most (if not all) of the reference errors have been corrected. If you notice that one or more of the problems you reported still exists, please create a new report from the "Edit this Page" link. In the future, please report issues separately rather than bundling them into a single issue.
