### ISSUE TITLE
Redirect /docs/asciidoctor.js/ to documentation site

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.org#996]
|Source|Destination|
| -- | -- |
|`https://asciidoctor.org/docs/asciidoctor.js/` | https://docs.asciidoctor.org/asciidoctor.js/latest/ |
|`https://asciidoctor.org/docs/asciidoctor.js/#quickstart` | https://docs.asciidoctor.org/asciidoctor.js/latest/setup/install/ |
|`https://asciidoctor.org/docs/asciidoctor.js/#learning` | https://docs.asciidoctor.org/asciidoctor.js/latest/setup/quick-tour/ |

Not sure what to do about:

##### `https://asciidoctor.org/docs/asciidoctor.js/#contributing`

Should we redirect to `https://github.com/asciidoctor/asciidoctor.js/blob/master/CONTRIBUTING.adoc`?

##### `https://asciidoctor.org/docs/asciidoctor.js/#copyright`

Should we redirect to `https://github.com/asciidoctor/asciidoctor.js/blob/master/LICENSE`?

**Comment by mojavelinux** [comment]
Sure. We still have to work out how to make the About the Project section consistent across projects. Some projects have this information in the docs, while others do not. Since Asciidoctor.js does not, it's best to redirect to the files in the GitHub repo (which I think should be done anyway). If we decide to change in the future, we can just update the mappings in this router.

**Comment by Mogztter** [comment]
@mojavelinux I noticed that redirects with complete URLs do not work, for instance: https://asciidoctor.org/docs/user-manual/#gradle

**Comment by mojavelinux** [comment]
Thanks for the heads up. I just applied a fix.
